#!/usr/bin/env bash
hyprctl devices -j | jq --raw-output '.keyboards[] | select(.name == "hoksi-technology-durgod-taurus-k320") | .active_keymap' | cut -c1-2 | tr \'[:upper:]\' \'[:lower:]\'
socat -u UNIX-CONNECT:/tmp/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock - | stdbuf -o0 awk -F '>>|,' '/^activelayout>>/{printf "%.2s\n", tolower($3)}'
