#!/bin/sh

status=$(nmcli g | grep -oE "disconnected")
essid=$(nmcli c | grep wlp1s0 | awk '{print ($1)}')

if [ $status ] ; then
    icon="󱘖 "
    text=""
else
    icon="󰖩 "
    text="${essid}"
fi

if [[ "$1" == "--essid" ]]; then
	echo $text
elif [[ "$1" == "--icon" ]]; then
	echo $icon
fi
