#!/bin/sh

status=$(nmcli g | grep -oE "disconnected")
essid=$(nmcli c | grep wlp1s0 | awk '{print ($1)}')

if [ $status ] ; then
    status="no con"
    text=""
else
    status="con"
    text="${essid}"
fi

if [[ "$1" == "--essid" ]]; then
	echo $text
elif [[ "$1" == "--status" ]]; then
	echo $status
fi
